name = "InterpretMe"
uuid = "e2b23942-74cb-440b-b3b6-a912e3f01750"
authors = ["Mohamed Mahrous"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[targets]
test = ["Test", "ScikitLearn", "RDatasets", "Conda", "PyCall"]
